postfix:
  image: htmlgraphic/postfix:latest
  container_name: postfix
  ports:
    - "25:25"
  restart: always
  environment:
    - DOMAIN=htmlgraphic.com
    - HOST=post-office
    - LOG_TOKEN=$(LOG_ENTRIES_TOKEN)
    - NODE_ENVIRONMENT=production
    - PASS=password
    - USER=username
